### PR TITLE
A working script for heroes

### PR DESCRIPTION
**Pull request by divy-work**
It gets all contributors of all the repos too.
And saves their json to json_api/heroes

### CODE REVIEW

**Comment by divy-work** [comment]
Please check if the script works fine. 
Regards.

**Comment by WeileiZeng** [comment]
https://github.com/WeileiZeng/Open-Source-COVID-19/commit/fe58a551399ec0a6cf4195fc3494fc23c822b8d0

It doesn't work directly for me. So I modified it to make libraries and indexes work. Meanwhile, I added a sample output.

I also create a data folder inside data+heroes/. We can put data for this part there if needed.

**Comment by WeileiZeng** [comment]
I add another test scripts heroes2.py this afternoon and encounter this issue.
* github search only return 30 result each time. one can manually increase to 100, and then change page numbers

Meanwhile, there is a gitter room, for faster and free communication.
[Gitter](https://gitter.im/OpenSourceCOVID-19/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by WeileiZeng** [comment]
I currently doesn't have time to work on it. But it is a super nice and even bigger idea that, given several related keywords, we can display its contributions on Github. Including how many repos, forks, stars, contributions, issues, and codes related to it. If it works, this function can live longer beyond this project.

**Comment by divy-work** [comment]
Sure! I'll join gitter and we can discuss there :)

**Pull request merged**
